In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [23]:
import math
def correlation_similarity(v1,v2):
    v1 = v1 - np.nanmean(v1)
    v2 = v2 - np.nanmean(v2)
    "compute similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
    sumxx, sumxy, sumyy = 0, 0, 0
    for i in range(len(v1)):
        x = v1[i]; y = v2[i]
        if np.isnan(x) or np.isnan(y) or x == 0 or y ==0: continue
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y
    if sumxx == 0 and sumyy == 0:
        sumxx = sumyy = 1
    return sumxy/math.sqrt(sumxx*sumyy)

def sim_matrix(M, dimension='user'):
    N = M.shape[0] if dimension == 'user' else M.shape[1]
    print("N=", N)
    sim = np.zeros([N,N])
    for i in range(N):
        for j in range(N):
            if i == j:
                sim[i,j] = 0 #Cancel out the effect of self-similarity in the sums later
                continue
            if dimension == 'user':
                v1, v2 = M[i,:], M[j,:]
            else:
                v1, v2 = M[:,i], M[:,j]
            sim[i][j] = correlation_similarity(v1,v2)
    print(sim.shape)
    return sim

In [13]:
df = pd.DataFrame(
        {"Course" : ["ICT", "Medicine", "Buisness", "Environment"],
        "Desperados" : [4, 1, np.nan, 4],
        "Guinness" : [3, 2, 2, 3],
        "Chimay Triple" : [2, 3, 1, np.nan],
        "Leffe" : [3, 1, np.nan, np.nan]})

df.head(16)

Course  Desperados  Guinness  Chimay Triple  Leffe
0          ICT         4.0         3            2.0    3.0
1     Medicine         1.0         2            3.0    1.0
2     Buisness         NaN         2            1.0    NaN
3  Environment         4.0         3            NaN    NaN

In [18]:
data_matrix = np.array([[4, 3, 2, 3],
               [1, 2, 3, 1],
               [np.nan, 2, 1, np.nan],
               [4, 3, np.nan, np.nan]])
print(data_matrix)

[[ 4.  3.  2.  3.]
 [ 1.  2.  3.  1.]
 [nan  2.  1. nan]
 [ 4.  3. nan nan]]


In [24]:
sim_matrix(data_matrix, 'user')

N= 4
(4, 4)


array([[ 0.        , -0.9701425 ,  1.        ,  1.        ],
       [-0.9701425 ,  0.        , -0.5547002 , -0.89442719],
       [ 1.        , -0.5547002 ,  0.        , -1.        ],
       [ 1.        , -0.89442719, -1.        ,  0.        ]])

In [25]:
sim_matrix(data_matrix, 'item')

N= 4
(4, 4)


array([[ 0.        ,  0.94280904, -1.        ,  0.9486833 ],
       [ 0.94280904,  0.        ,  0.        ,  1.        ],
       [-1.        ,  0.        ,  0.        , -1.        ],
       [ 0.9486833 ,  1.        , -1.        ,  0.        ]])